---
title: "Learning Cyber Security - Initiative"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

# Master Cyber Security

We base our Initiative: Master Cyber Security on Planning a [Minimum Viable Nothing (MVN)](https://github.com/vanHeemstraSystems/minimum-viable-nothing).

At the very beginning, you should have identified a need as to why the product (i.e., good or service) should exist. This could be an organizational need or a customer need that addresses a current gap.

## 1. Identify and understand the **Business Needs**.

### a) Determine the **long-term goal** of the product (i.e., good or service) and write it down.

The long-term goal of mastering cyber security is to prevent and/or mitigate risks of loss or theft of valuable information (including intellectual property, secrets, and other sensitive data).

### b) Answer the question "**Why are we doing this project?**"

The reason for mastering cyber security is to obtain the knowledge and train the practise of preventing and /or mitigating risks of loss or theft of valuable information.

### c) Identify the **success criteria** that will indicate whether or not the product (i.e., good or service) is successful.

[If you master something, you learn how to do it properly or you succeed in understanding it completely.](https://www.collinsdictionary.com/dictionary/english/master-a-subject#:~:text=If%20you%20master%20something%2C%20you,succeed%20in%20understanding%20it%20completely.) 

Hence, mastering cyber security has been successful if we either ```learn how to do it properly``` or we ```succeed in understanding it completely```.
